### ISSUE TITLE
Update stable version in repo from 0.0.0 to 1.1.0

### ISSUE THREAD

**Issue by GermanBluefox** [ChrisWbb/ioBroker.sonnen-charger#70]
# Think about adding version 1.1.0 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**1.1.0** (227 days old)
**Installs**: stable=**0** (0%), latest=**2** (25%), total=**8**

Click to use [developer portal](https://www.iobroker.dev/adapter/sonnen-charger/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by mcm1957** [comment]
wait for 1.2.1

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 1.1.0 but in the meantime an update to version 1.2.1 is suggested.

So this issue will be closed and replaced by an updated one.

@mcm1957 for evidence
